CREATE TABLE `training_center`.`measurements` (
  `MSR_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Measurement ID',
  `MSR_AUDIT_CD` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Measurement creation date',
  `MSR_AUDIT_CU` INT NULL COMMENT 'Measurement creation user',
  `MSR_AUDIT_MD` DATETIME NULL COMMENT 'Measurement modification date',
  `MSR_AUDIT_MU` INT NULL COMMENT 'Measurement modification user',
  `MSR_AUDIT_RD` DATETIME NULL COMMENT 'Measurement removal date',
  `MSR_AUDIT_RU` INT NULL COMMENT 'Measurement removal user',
  `MSR_DATE` DATETIME NOT NULL COMMENT 'Measurement date',
  `MSR_HEIGHT` DOUBLE NULL COMMENT 'Height in cm',
  `MSR_WEIGHT` DOUBLE NULL COMMENT 'Weight in kg',
  `MSR_CALF` DOUBLE NULL COMMENT 'Calf measurement in cm',
  `MSR_THIGH` DOUBLE NULL COMMENT 'Thigh measurement in cm',
  `MSR_LOINS` DOUBLE NULL COMMENT 'Loins measurement in cm',
  `MSR_HIPS` DOUBLE NULL COMMENT 'Hips measurement in cm',
  `MSR_WAIST` DOUBLE NULL COMMENT 'Waist measurement in cm',
  `MSR_ABDOMEN` DOUBLE NULL COMMENT 'Abdomen measurement in cm',
  `MSR_CHEST` DOUBLE NULL COMMENT 'Chest measurement in cm',
  `MSR_SHOULDERS` DOUBLE NULL COMMENT 'Shoulders measurement in cm',
  `MSR_TRICEPS` DOUBLE NULL COMMENT 'Triceps measurement in cm',
  `MSR_BICEPS` DOUBLE NULL COMMENT 'Biceps measurement in cm',
  `MSR_FOREARM` DOUBLE NULL COMMENT 'Forearm measurement in cm',
  `MSR_WRIST` DOUBLE NULL COMMENT 'Wrist measurement in cm',
  `ACC_ID` INT NOT NULL COMMENT 'Account ID',
  INDEX `MSR_ACC_FK_IDX` (`ACC_ID` ASC),
  CONSTRAINT `MSR_ACC_FK`
    FOREIGN KEY (`ACC_ID`)
    REFERENCES `ACCOUNTS` (`ACC_ID`),
  PRIMARY KEY (`MSR_ID`));
