CREATE TABLE `TRAINING_CENTER`.`TRAINING_PLANS_TEMPLATES` (
  `TPT_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Training plan template ID',
  `TPT_AUDIT_CD` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT 'Training plan creation date',
  `TPT_AUDIT_CU` INT UNSIGNED COMMENT 'Training plan creation user',
  `TPT_AUDIT_MD` DATETIME COMMENT 'Training plan modification date',
  `TPT_AUDIT_MU` INT UNSIGNED COMMENT 'Training plan modification user',
  `TPT_AUDIT_RD` DATETIME COMMENT 'Training plan removal date',
  `TPT_AUDIT_RU` INT UNSIGNED COMMENT 'Training plan removal user',
  `TPT_NAME` VARCHAR(45) DEFAULT NULL COMMENT 'Training plan template name',
  `ACC_ID` INT NOT NULL COMMENT 'Training plan owner ID',
  PRIMARY KEY (`TPT_ID`),
  INDEX `ACCOUNT_FK_IDX` (`ACC_ID` ASC),
  CONSTRAINT `TPT_ACCOUNT_FK`
    FOREIGN KEY (`ACC_ID`)
    REFERENCES `ACCOUNTS` (`ACC_ID`)
);

CREATE TABLE `TRAINING_CENTER`.`TRAINING_SERIES_RESULTS` (
  `TSR_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Training series results ID',
  `TSR_ITERATION_UNIT` VARCHAR(45) DEFAULT NULL COMMENT 'Iteration unit',
  `TSR_ITERATION_COUNT` DOUBLE DEFAULT NULL COMMENT 'Iteration count',
  `TSR_ADDL_WEIGHT` DOUBLE DEFAULT NULL COMMENT 'Additional weight',
  `TSR_RESULT` DOUBLE DEFAULT NULL COMMENT 'Training series result',
  PRIMARY KEY (`TSR_ID`)
);

CREATE TABLE `TRAINING_CENTER`.`TRAININGS_HISTORY` (
  `THI_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Training history ID',
  `THI_AUDIT_CD` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT 'Training history creation date',
  `THI_AUDIT_CU` INT UNSIGNED COMMENT 'Training history creation user',
  `THI_AUDIT_MD` DATETIME COMMENT 'Training history modification date',
  `THI_AUDIT_MU` INT UNSIGNED COMMENT 'Training history modification user',
  `THI_AUDIT_RD` DATETIME COMMENT 'Training history removal date',
  `THI_AUDIT_RU` INT UNSIGNED COMMENT 'Training history removal user',
  `THI_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Training date',
  `ACC_ID` INT DEFAULT NULL COMMENT 'Account ID',
  PRIMARY KEY (`THI_ID`),
  INDEX `ACCOUNT_FK_IDX` (`ACC_ID` ASC),
  CONSTRAINT `THI_ACCOUNT_FK`
    FOREIGN KEY (`ACC_ID`)
    REFERENCES `ACCOUNTS` (`ACC_ID`)
);

CREATE TABLE `TRAINING_CENTER`.`TRAINING_SERIES` (
  `TSE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Training series ID',
  `TSE_AUDIT_CD` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT 'Training series creation date',
  `TSE_AUDIT_CU` INT UNSIGNED COMMENT 'Training series creation user',
  `TSE_AUDIT_MD` DATETIME COMMENT 'Training series modification date',
  `TSE_AUDIT_MU` INT UNSIGNED COMMENT 'Training series modification user',
  `TSE_AUDIT_RD` DATETIME COMMENT 'Training series removal date',
  `TSE_AUDIT_RU` INT UNSIGNED COMMENT 'Training series removal user',
  `TSE_THI_ID` INT UNSIGNED DEFAULT NULL COMMENT 'Training ID',
  `TSE_EXC_ID` INT UNSIGNED DEFAULT NULL COMMENT 'Exercise ID',
  `TSE_UNIT` INT UNSIGNED DEFAULT NULL COMMENT 'Training unit',
  `TSE_TSR_ID` INT UNSIGNED DEFAULT NULL COMMENT 'Training series result ID',
  PRIMARY KEY (`TSE_ID`),
  INDEX `TSE_THI_FK_IDX` (`TSE_THI_ID` ASC),
  INDEX `TSE_EXC_FK_IDX` (`TSE_EXC_ID` ASC),
  INDEX `TSE_TSR_FK_IDX` (`TSE_TSR_ID` ASC),
  CONSTRAINT `TSE_TRAINING_HISTORY_FK`
    FOREIGN KEY (`TSE_THI_ID`)
    REFERENCES `TRAININGS_HISTORY` (`THI_ID`),
  CONSTRAINT `TSE_EXCERCISE_FK`
    FOREIGN KEY (`TSE_EXC_ID`)
    REFERENCES `EXERCISES` (`EXC_ID`),
  CONSTRAINT `TSE_TRAINING_RESULT_FK`
    FOREIGN KEY (`TSE_TSR_ID`)
    REFERENCES `TRAINING_SERIES_RESULTS` (`TSR_ID`)
);

CREATE TABLE `TRAINING_CENTER`.`TRAINING_SERIES_TEMPLATE` (
  `TST_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Training series template ID',
  `TST_AUDIT_CD` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT 'Training series template creation date',
  `TST_AUDIT_CU` INT UNSIGNED COMMENT 'Training series template creation user',
  `TST_AUDIT_MD` DATETIME COMMENT 'Training series template modification date',
  `TST_AUDIT_MU` INT UNSIGNED COMMENT 'Training series template modification user',
  `TST_AUDIT_RD` DATETIME COMMENT 'Training series template removal date',
  `TST_AUDIT_RU` INT UNSIGNED COMMENT 'Training series template removal user',
  `TST_TPT_ID` INT UNSIGNED DEFAULT NULL COMMENT 'Training plan template ID',
  `TST_EXC_ID` INT UNSIGNED DEFAULT NULL COMMENT 'Exercise ID',
  `TST_UNIT` INT UNSIGNED DEFAULT NULL COMMENT 'Training unit',
  PRIMARY KEY (`TST_ID`),
  INDEX `PLAN_TEMPLATE_ID_IDX` (`TST_TPT_ID` ASC),
  INDEX `EXERCISE_FK_IDX` (`TST_EXC_ID` ASC),
  CONSTRAINT `TST_TEMPLATE_FK`
    FOREIGN KEY (`TST_TPT_ID`)
    REFERENCES `TRAINING_PLANS_TEMPLATES` (`TPT_ID`),
  CONSTRAINT `TST_EXERCISE_FK`
    FOREIGN KEY (`TST_EXC_ID`)
    REFERENCES `EXERCISES` (`EXC_ID`)
);