CREATE TABLE `TRAINING_CENTER`.`ACCOUNT_ROLE` (
  `ACC_ID` INT NULL,
  `ROL_ID` INT NULL,
  INDEX `ACC_ID_idx` (`ACC_ID` ASC),
  INDEX `ROL_ID_idx` (`ROL_ID` ASC),
  CONSTRAINT `ACC_ID`
    FOREIGN KEY (`ACC_ID`)
    REFERENCES `training_center`.`accounts` (`ACC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ROL_ID`
    FOREIGN KEY (`ROL_ID`)
    REFERENCES `training_center`.`roles` (`ROL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    );
