ALTER TABLE `TRAINING_CENTER`.`ACCOUNTS`
ADD COLUMN `ACC_FIRST_NAME` VARCHAR(50) COMMENT 'Account owner first name',
ADD COLUMN `ACC_LAST_NAME` VARCHAR(100) COMMENT 'Account owner last name',
ADD COLUMN `ACC_IDENTIFIER` VARCHAR(50) COMMENT 'Account identifier',
ADD COLUMN `ACC_BIRTHDATE` VARCHAR(50) COMMENT 'Account owner birthdate',
ADD COLUMN `ACC_DESCRIPTION` VARCHAR(255) COMMENT 'Account description';